Git flow support
subesokun/atom-tree-view-git-status pull request #47
Opened 2017-03-25 16:57 UTC by roelofr

Git flow is a fairly properly worked out system with clear branch name distinctions, but I couldn't see it when I was using this plugin.

Therefore, I came up with a way to show the git flow types in the header, using a combination of icons and labels (user configurable).

Some screenshots:

**Enabled with both prefix and icon visible**
![6 repositories with both icon and prefix visible](https://cloud.githubusercontent.com/assets/1771026/24324266/b091fbee-1183-11e7-856f-84ecb40c9876.png)

**Enabled with  the prefix and branch name visible** (this is the default display method)
![Just the prefix and branch name (default value)](https://cloud.githubusercontent.com/assets/1771026/24324289/f87c478e-1183-11e7-8ae2-fcd55678af85.png)

**Only the icon and branch name** - I chose to always show the branch on `master` and `develop`, since using just an icon on such important branches is never a good idea.
![Just the icon](https://cloud.githubusercontent.com/assets/1771026/24324290/f87cf27e-1183-11e7-8805-e288f28d2526.png)

By default the tweak is disabled, as git flow is an explicit opt in. If the repository doesn't have git flow support (`git flow init` hasn't been run) the tweak disables itself.

The prefixes and branch names for `master` and `develop` are retrieved from the repository itself, which makes using custom prefixes and branch names a piece of cake.

Hope this is any use to you.

2017-03-26 18:15 UTC, subesokun commented
@roelofr Thanks a lot for your awesome contribution! It perfectly fits the idea of this package so I'll gladly review your code 😎 . But I'm not sure if I can prepare a new release until next week.

2017-03-26 19:03 UTC, roelofr commented
That's all right. All in good time :wink:

2017-04-06 17:14 UTC, subesokun requested changes
Initial review :)

2017-04-06 17:14 UTC, subesokun commented on lib/gitrepositoryasync.coffee
> +  getFlowConfig: ->
The `lib/gitrepositoryasync.coffee` should just be a wrapper for the Atom GitRepository with the exact same API.
Move to `lib/gitflow.coffee`

2017-04-06 17:14 UTC, subesokun commented on lib/treeviewui.coffee
> +flowIconMap =
Move to `lib/gitflow.coffee`

2017-04-06 17:14 UTC, subesokun commented on lib/treeviewui.coffee
> +    @gitFlowEnabled =
Move to `lib/gitflow.coffee`

2017-04-06 17:14 UTC, subesokun commented on lib/treeviewui.coffee
> +    @subscriptions.add(
Move to `lib/gitflow.coffee`

2017-04-06 17:14 UTC, subesokun commented on lib/treeviewui.coffee
> +  ###
Move to `lib/gitflow.coffee`

2017-04-06 17:14 UTC, subesokun commented on styles/tree-view-git-status.less
> +
Move to `styles/gitflow.less `

2017-04-06 17:14 UTC, subesokun commented on styles/variables.less
> +@import 'ui-variables';
Move to `styles/gitflow.less`

2017-04-07 12:03 UTC, roelofr commented
Okay, I separated most of the code responsible for handling the git flow parameters. There are only a handful of changes to the logic to make it work. The exact changes [are listed in this gist][1]

[1]: https://gist.github.com/roelofr/4e42c725c881b6152ddd2f8c66d258c9

2017-04-14 08:01 UTC, subesokun approved these changes

2017-04-19 16:27 UTC, subesokun commented
Sorry for the delay, other work is recently piling up so I didn't have any chance yet to prepare a new release. Hopefully not somebody else is already eagerly looking forward to that feature. Also there seems to be something off on the master branch regarding the Atom Beta tests. So I'd need to fix that as well before releasing a new version.

2017-04-22 09:18 UTC, closed without merging

2017-04-22 09:19 UTC, subesokun commented
Merged but release is pending. Thanks a lot for this great feature!

2017-05-21 17:18 UTC, subesokun commented
Finally fixed the build issues and released `v1.4.0` 🎉 ! There has been some breaking changes in the tree-view package in the latest Atom beta release. I've also updated the documentation to install [gitflow-avh](https://github.com/petervanderdoes/gitflow-avh) as this fork seems to be still active and it implements the Git Flow "support" branches.

Sorry for the huge delay. Let me know if you've facing any issues. Btw. I've enabled the Git Flow support by default 👍

2017-05-23 18:58 UTC, radAragon commented
Report: I see the gray color on my master branch (actually named "releases") but the icon is missing.

Below is my configuration:
```
[gitflow "branch"]
	master = releases
	develop = develop
[gitflow "prefix"]
	feature = feature/
	bugfix = bugfix/
	release = qa
	hotfix = hotfix/
	support = support/
	versiontag =
```

PS: love this upgrade

2017-05-23 20:04 UTC, subesokun commented
@radAragon This is the default display type so you'd need to change that in the package settings of tree-view-git-status.

2017-05-23 20:43 UTC, radAragon commented
Sorry, I forgot to tell I already set this option to icon/branch name, so the develop, qa and features branches already display the icon, but the master. :/

2017-05-26 06:34 UTC, subesokun commented
@radAragon Ok I see, I'll try to investigate it but it would help if you're creating a dedicated issue for it so that we can track the progress there.